### ISSUE TITLE
govendor stuff is missing

### ISSUE THREAD

**Issue by xnox** [chrisccoulson/ubuntu-core-fde-utils#13]
prepare.sh from spike-tools expects a `/vendor` subdirectory that can be used with govendor. However, there isn't one here.

See https://github.com/snapcore/spike-tools/pull/5

**Comment by cmatsuoka** [comment]
We used to have vendored packages in fde-utils but since the migration to `go-tpm2` they were removed. https://github.com/snapcore/spike-tools/pull/17 addresses that.
